server:
  port: 9092

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ahmet
    password: 020900
    url: jdbc:postgresql://localhost:5432/authdb_rituelpazarlama
data:
    redis:
      host: localhost
      port: 6379
      password: "1alexdegil41*?"
jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: b85ad78baba523b5c1d307c5bf9b96ac1d5c099f56787539f9a2ed3aae
  expiration: 3600000
  refresh-token:
    expiration-ms: 1209600000
